package api

const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Select Locations</title>
</head>
<body>
    <h1>Select Locations</h1>
    <form action="/submit" method="post">
    <label for="from">From:</label>

    <select id="from" name="from">
  		<option value="1">Newark Airport</option>
  		<option value="2" selected>Jamaica Bay</option>
  		<option value="3">Allerton/Pelham Gardens</option>
  		<option value="4">Alphabet City</option>
  		<option value="5">Arden Heights</option>
  		<option value="6">Arrochar/Fort Wadsworth</option>
  		<option value="7">Astoria</option>
  		<option value="8">Astoria Park</option>
  		<option value="9">Auburndale</option>
  		<option value="10">Baisley Park</option>
  		<option value="11">Bath Beach</option>
  		<option value="12">Battery Park</option>
  		<option value="13">Battery Park City</option>
  		<option value="14">Bay Ridge</option>
  		<option value="15">Bay Terrace/Fort Totten</option>
  		<option value="16">Bayside</option>
  		<option value="17">Bedford</option>
  		<option value="18">Bedford Park</option>
  		<option value="19">Bellerose</option>
  		<option value="20">Belmont</option>
  		<option value="21">Bensonhurst East</option>
  		<option value="22">Bensonhurst West</option>
  		<option value="23">Bloomfield/Emerson Hill</option>
  		<option value="24">Bloomingdale</option>
  		<option value="25">Boerum Hill</option>
  		<option value="26">Borough Park</option>
  		<option value="27">Breezy Point/Fort Tilden/Riis Beach</option>
  		<option value="28">Briarwood/Jamaica Hills</option>
  		<option value="29">Brighton Beach</option>
  		<option value="30">Broad Channel</option>
  		<option value="31">Bronx Park</option>
  		<option value="32">Bronxdale</option>
  		<option value="33">Brooklyn Heights</option>
  		<option value="34">Brooklyn Navy Yard</option>
  		<option value="35">Brownsville</option>
  		<option value="36">Bushwick North</option>
  		<option value="37">Bushwick South</option>
  		<option value="38">Cambria Heights</option>
  		<option value="39">Canarsie</option>
  		<option value="40">Carroll Gardens</option>
  		<option value="41">Central Harlem</option>
  		<option value="42">Central Harlem North</option>
  		<option value="43">Central Park</option>
  		<option value="44">Charleston/Tottenville</option>
  		<option value="45">Chinatown</option>
  		<option value="46">City Island</option>
  		<option value="47">Claremont/Bathgate</option>
  		<option value="48">Clinton East</option>
  		<option value="49">Clinton Hill</option>
  		<option value="50">Clinton West</option>
  		<option value="51">Co-Op City</option>
  		<option value="52">Cobble Hill</option>
  		<option value="53">College Point</option>
  		<option value="54">Columbia Street</option>
  		<option value="55">Coney Island</option>
  		<option value="56">Corona</option>
  		<option value="57">Corona</option>
  		<option value="58">Country Club</option>
  		<option value="59">Crotona Park</option>
  		<option value="60">Crotona Park East</option>
  		<option value="61">Crown Heights North</option>
  		<option value="62">Crown Heights South</option>
  		<option value="63">Cypress Hills</option>
  		<option value="64">Douglaston</option>
  		<option value="65">Downtown Brooklyn/MetroTech</option>
  		<option value="66">DUMBO/Vinegar Hill</option>
  		<option value="67">Dyker Heights</option>
  		<option value="68">East Chelsea</option>
  		<option value="69">East Concourse/Concourse Village</option>
  		<option value="70">East Elmhurst</option>
  		<option value="71">East Flatbush/Farragut</option>
  		<option value="72">East Flatbush/Remsen Village</option>
  		<option value="73">East Flushing</option>
  		<option value="74">East Harlem North</option>
  		<option value="75">East Harlem South</option>
  		<option value="76">East New York</option>
  		<option value="77">East New York/Pennsylvania Avenue</option>
  		<option value="78">East Tremont</option>
  		<option value="79">East Village</option>
  		<option value="80">East Williamsburg</option>
  		<option value="81">Eastchester</option>
  		<option value="82">Elmhurst</option>
  		<option value="83">Elmhurst/Maspeth</option>
  		<option value="84">Eltingville/Annadale/Prince's Bay</option>
  		<option value="85">Erasmus</option>
  		<option value="86">Far Rockaway</option>
  		<option value="87">Financial District North</option>
  		<option value="88">Financial District South</option>
  		<option value="89">Flatbush/Ditmas Park</option>
  		<option value="90">Flatiron</option>
  		<option value="91">Flatlands</option>
  		<option value="92">Flushing</option>
  		<option value="93">Flushing Meadows-Corona Park</option>
  		<option value="94">Fordham South</option>
  		<option value="95">Forest Hills</option>
  		<option value="96">Forest Park/Highland Park</option>
  		<option value="97">Fort Greene</option>
  		<option value="98">Fresh Meadows</option>
  		<option value="99">Freshkills Park</option>
  		<option value="100">Garment District</option>
  		<option value="101">Glen Oaks</option>
  		<option value="102">Glendale</option>
  		<option value="103">Governor's Island/Ellis Island/Liberty Island</option>
  		<option value="104">Governor's Island/Ellis Island/Liberty Island</option>
  		<option value="105">Governor's Island/Ellis Island/Liberty Island</option>
  		<option value="106">Gowanus</option>
  		<option value="107">Gramercy</option>
  		<option value="108">Gravesend</option>
  		<option value="109">Great Kills</option>
  		<option value="110">Great Kills Park</option>
  		<option value="111">Green-Wood Cemetery</option>
  		<option value="112">Greenpoint</option>
  		<option value="113">Greenwich Village North</option>
  		<option value="114">Greenwich Village South</option>
  		<option value="115">Grymes Hill/Clifton</option>
  		<option value="116">Hamilton Heights</option>
  		<option value="117">Hammels/Arverne</option>
  		<option value="118">Heartland Village/Todt Hill</option>
  		<option value="119">Highbridge</option>
  		<option value="120">Highbridge Park</option>
  		<option value="121">Hillcrest/Pomonok</option>
  		<option value="122">Hollis</option>
  		<option value="123">Homecrest</option>
  		<option value="124">Howard Beach</option>
  		<option value="125">Hudson Sq</option>
  		<option value="126">Hunts Point</option>
  		<option value="127">Inwood</option>
  		<option value="128">Inwood Hill Park</option>
  		<option value="129">Jackson Heights</option>
  		<option value="130">Jamaica</option>
  		<option value="131">Jamaica Estates</option>
  		<option value="132">JFK Airport</option>
  		<option value="133">Kensington</option>
  		<option value="134">Kew Gardens</option>
  		<option value="135">Kew Gardens Hills</option>
  		<option value="136">Kingsbridge Heights</option>
  		<option value="137">Kips Bay</option>
  		<option value="138">LaGuardia Airport</option>
  		<option value="139">Laurelton</option>
  		<option value="140">Lenox Hill East</option>
  		<option value="141">Lenox Hill West</option>
  		<option value="142">Lincoln Square East</option>
  		<option value="143">Lincoln Square West</option>
  		<option value="144">Little Italy/NoLiTa</option>
  		<option value="145">Long Island City/Hunters Point</option>
  		<option value="146">Long Island City/Queens Plaza</option>
  		<option value="147">Longwood</option>
  		<option value="148">Lower East Side</option>
  		<option value="149">Madison</option>
  		<option value="150">Manhattan Beach</option>
  		<option value="151">Manhattan Valley</option>
  		<option value="152">Manhattanville</option>
  		<option value="153">Marble Hill</option>
  		<option value="154">Marine Park/Floyd Bennett Field</option>
  		<option value="155">Marine Park/Mill Basin</option>
  		<option value="156">Mariners Harbor</option>
  		<option value="157">Maspeth</option>
  		<option value="158">Meatpacking/West Village West</option>
  		<option value="159">Melrose South</option>
  		<option value="160">Middle Village</option>
  		<option value="161">Midtown Center</option>
  		<option value="162">Midtown East</option>
  		<option value="163">Midtown North</option>
  		<option value="164">Midtown South</option>
  		<option value="165">Midwood</option>
  		<option value="166">Morningside Heights</option>
  		<option value="167">Morrisania/Melrose</option>
  		<option value="168">Mott Haven/Port Morris</option>
  		<option value="169">Mount Hope</option>
  		<option value="170">Murray Hill</option>
  		<option value="171">Murray Hill-Queens</option>
  		<option value="172">New Dorp/Midland Beach</option>
  		<option value="173">North Corona</option>
  		<option value="174">Norwood</option>
  		<option value="175">Oakland Gardens</option>
  		<option value="176">Oakwood</option>
  		<option value="177">Ocean Hill</option>
  		<option value="178">Ocean Parkway South</option>
  		<option value="179">Old Astoria</option>
  		<option value="180">Ozone Park</option>
  		<option value="181">Park Slope</option>
  		<option value="182">Parkchester</option>
  		<option value="183">Pelham Bay</option>
  		<option value="184">Pelham Bay Park</option>
  		<option value="185">Pelham Parkway</option>
  		<option value="186">Penn Station/Madison Sq West</option>
  		<option value="187">Port Richmond</option>
  		<option value="188">Prospect-Lefferts Gardens</option>
  		<option value="189">Prospect Heights</option>
  		<option value="190">Prospect Park</option>
  		<option value="191">Queens Village</option>
  		<option value="192">Queensboro Hill</option>
  		<option value="193">Queensbridge/Ravenswood</option>
  		<option value="194">Randalls Island</option>
  		<option value="195">Red Hook</option>
  		<option value="196">Rego Park</option>
  		<option value="197">Richmond Hill</option>
  		<option value="198">Ridgewood</option>
  		<option value="199">Rikers Island</option>
  		<option value="200">Riverdale/North Riverdale/Fieldston</option>
  		<option value="201">Rockaway Park</option>
  		<option value="202">Roosevelt Island</option>
  		<option value="203">Rosedale</option>
  		<option value="204">Rossville/Woodrow</option>
  		<option value="205">Saint Albans</option>
  		<option value="206">Saint George/New Brighton</option>
  		<option value="207">Saint Michaels Cemetery/Woodside</option>
  		<option value="208">Schuylerville/Edgewater Park</option>
  		<option value="209">Seaport</option>
  		<option value="210">Sheepshead Bay</option>
  		<option value="211">SoHo</option>
  		<option value="212">Soundview/Bruckner</option>
  		<option value="213">Soundview/Castle Hill</option>
  		<option value="214">South Beach/Dongan Hills</option>
  		<option value="215">South Jamaica</option>
  		<option value="216">South Ozone Park</option>
  		<option value="217">South Williamsburg</option>
  		<option value="218">Springfield Gardens North</option>
  		<option value="219">Springfield Gardens South</option>
  		<option value="220">Spuyten Duyvil/Kingsbridge</option>
  		<option value="221">Stapleton</option>
  		<option value="222">Starrett City</option>
  		<option value="223">Steinway</option>
  		<option value="224">Stuy Town/Peter Cooper Village</option>
  		<option value="225">Stuyvesant Heights</option>
  		<option value="226">Sunnyside</option>
  		<option value="227">Sunset Park East</option>
  		<option value="228">Sunset Park West</option>
  		<option value="229">Sutton Place/Turtle Bay North</option>
  		<option value="230">Times Sq/Theatre District</option>
  		<option value="231">TriBeCa/Civic Center</option>
  		<option value="232">Two Bridges/Seward Park</option>
  		<option value="233">UN/Turtle Bay South</option>
  		<option value="234">Union Sq</option>
  		<option value="235">University Heights/Morris Heights</option>
  		<option value="236">Upper East Side North</option>
  		<option value="237">Upper East Side South</option>
  		<option value="238">Upper West Side North</option>
  		<option value="239">Upper West Side South</option>
  		<option value="240">Van Cortlandt Park</option>
  		<option value="241">Van Cortlandt Village</option>
  		<option value="242">Van Nest/Morris Park</option>
  		<option value="243">Washington Heights North</option>
  		<option value="244">Washington Heights South</option>
  		<option value="245">West Brighton</option>
  		<option value="246">West Chelsea/Hudson Yards</option>
  		<option value="247">West Concourse</option>
  		<option value="248">West Farms/Bronx River</option>
  		<option value="249">West Village</option>
  		<option value="250">Westchester Village/Unionport</option>
  		<option value="251">Westerleigh</option>
  		<option value="252">Whitestone</option>
  		<option value="253">Willets Point</option>
  		<option value="254">Williamsbridge/Olinville</option>
  		<option value="255">Williamsburg (North Side)</option>
  		<option value="256">Williamsburg (South Side)</option>
  		<option value="257">Windsor Terrace</option>
  		<option value="258">Woodhaven</option>
  		<option value="259">Woodlawn/Wakefield</option>
  		<option value="260">Woodside</option>
  		<option value="261">World Trade Center</option>
  		<option value="262">Yorkville East</option>
  		<option value="263">Yorkville West</option>
  		<option value="264">N/A</option>
  		<option value="265">Outside of NYC</option>
    </select>

    <br><br>

    <label for="to">To:</label>

    <select id="to" name="to">
  		<option value="1">Newark Airport</option>
  		<option value="2">Jamaica Bay</option>
  		<option value="3" selected>Allerton/Pelham Gardens</option>
  		<option value="4">Alphabet City</option>
  		<option value="5">Arden Heights</option>
  		<option value="6">Arrochar/Fort Wadsworth</option>
  		<option value="7">Astoria</option>
  		<option value="8">Astoria Park</option>
  		<option value="9">Auburndale</option>
  		<option value="10">Baisley Park</option>
  		<option value="11">Bath Beach</option>
  		<option value="12">Battery Park</option>
  		<option value="13">Battery Park City</option>
  		<option value="14">Bay Ridge</option>
  		<option value="15">Bay Terrace/Fort Totten</option>
  		<option value="16">Bayside</option>
  		<option value="17">Bedford</option>
  		<option value="18">Bedford Park</option>
  		<option value="19">Bellerose</option>
  		<option value="20">Belmont</option>
  		<option value="21">Bensonhurst East</option>
  		<option value="22">Bensonhurst West</option>
  		<option value="23">Bloomfield/Emerson Hill</option>
  		<option value="24">Bloomingdale</option>
  		<option value="25">Boerum Hill</option>
  		<option value="26">Borough Park</option>
  		<option value="27">Breezy Point/Fort Tilden/Riis Beach</option>
  		<option value="28">Briarwood/Jamaica Hills</option>
  		<option value="29">Brighton Beach</option>
  		<option value="30">Broad Channel</option>
  		<option value="31">Bronx Park</option>
  		<option value="32">Bronxdale</option>
  		<option value="33">Brooklyn Heights</option>
  		<option value="34">Brooklyn Navy Yard</option>
  		<option value="35">Brownsville</option>
  		<option value="36">Bushwick North</option>
  		<option value="37">Bushwick South</option>
  		<option value="38">Cambria Heights</option>
  		<option value="39">Canarsie</option>
  		<option value="40">Carroll Gardens</option>
  		<option value="41">Central Harlem</option>
  		<option value="42">Central Harlem North</option>
  		<option value="43">Central Park</option>
  		<option value="44">Charleston/Tottenville</option>
  		<option value="45">Chinatown</option>
  		<option value="46">City Island</option>
  		<option value="47">Claremont/Bathgate</option>
  		<option value="48">Clinton East</option>
  		<option value="49">Clinton Hill</option>
  		<option value="50">Clinton West</option>
  		<option value="51">Co-Op City</option>
  		<option value="52">Cobble Hill</option>
  		<option value="53">College Point</option>
  		<option value="54">Columbia Street</option>
  		<option value="55">Coney Island</option>
  		<option value="56">Corona</option>
  		<option value="57">Corona</option>
  		<option value="58">Country Club</option>
  		<option value="59">Crotona Park</option>
  		<option value="60">Crotona Park East</option>
  		<option value="61">Crown Heights North</option>
  		<option value="62">Crown Heights South</option>
  		<option value="63">Cypress Hills</option>
  		<option value="64">Douglaston</option>
  		<option value="65">Downtown Brooklyn/MetroTech</option>
  		<option value="66">DUMBO/Vinegar Hill</option>
  		<option value="67">Dyker Heights</option>
  		<option value="68">East Chelsea</option>
  		<option value="69">East Concourse/Concourse Village</option>
  		<option value="70">East Elmhurst</option>
  		<option value="71">East Flatbush/Farragut</option>
  		<option value="72">East Flatbush/Remsen Village</option>
  		<option value="73">East Flushing</option>
  		<option value="74">East Harlem North</option>
  		<option value="75">East Harlem South</option>
  		<option value="76">East New York</option>
  		<option value="77">East New York/Pennsylvania Avenue</option>
  		<option value="78">East Tremont</option>
  		<option value="79">East Village</option>
  		<option value="80">East Williamsburg</option>
  		<option value="81">Eastchester</option>
  		<option value="82">Elmhurst</option>
  		<option value="83">Elmhurst/Maspeth</option>
  		<option value="84">Eltingville/Annadale/Prince's Bay</option>
  		<option value="85">Erasmus</option>
  		<option value="86">Far Rockaway</option>
  		<option value="87">Financial District North</option>
  		<option value="88">Financial District South</option>
  		<option value="89">Flatbush/Ditmas Park</option>
  		<option value="90">Flatiron</option>
  		<option value="91">Flatlands</option>
  		<option value="92">Flushing</option>
  		<option value="93">Flushing Meadows-Corona Park</option>
  		<option value="94">Fordham South</option>
  		<option value="95">Forest Hills</option>
  		<option value="96">Forest Park/Highland Park</option>
  		<option value="97">Fort Greene</option>
  		<option value="98">Fresh Meadows</option>
  		<option value="99">Freshkills Park</option>
  		<option value="100">Garment District</option>
  		<option value="101">Glen Oaks</option>
  		<option value="102">Glendale</option>
  		<option value="103">Governor's Island/Ellis Island/Liberty Island</option>
  		<option value="104">Governor's Island/Ellis Island/Liberty Island</option>
  		<option value="105">Governor's Island/Ellis Island/Liberty Island</option>
  		<option value="106">Gowanus</option>
  		<option value="107">Gramercy</option>
  		<option value="108">Gravesend</option>
  		<option value="109">Great Kills</option>
  		<option value="110">Great Kills Park</option>
  		<option value="111">Green-Wood Cemetery</option>
  		<option value="112">Greenpoint</option>
  		<option value="113">Greenwich Village North</option>
  		<option value="114">Greenwich Village South</option>
  		<option value="115">Grymes Hill/Clifton</option>
  		<option value="116">Hamilton Heights</option>
  		<option value="117">Hammels/Arverne</option>
  		<option value="118">Heartland Village/Todt Hill</option>
  		<option value="119">Highbridge</option>
  		<option value="120">Highbridge Park</option>
  		<option value="121">Hillcrest/Pomonok</option>
  		<option value="122">Hollis</option>
  		<option value="123">Homecrest</option>
  		<option value="124">Howard Beach</option>
  		<option value="125">Hudson Sq</option>
  		<option value="126">Hunts Point</option>
  		<option value="127">Inwood</option>
  		<option value="128">Inwood Hill Park</option>
  		<option value="129">Jackson Heights</option>
  		<option value="130">Jamaica</option>
  		<option value="131">Jamaica Estates</option>
  		<option value="132">JFK Airport</option>
  		<option value="133">Kensington</option>
  		<option value="134">Kew Gardens</option>
  		<option value="135">Kew Gardens Hills</option>
  		<option value="136">Kingsbridge Heights</option>
  		<option value="137">Kips Bay</option>
  		<option value="138">LaGuardia Airport</option>
  		<option value="139">Laurelton</option>
  		<option value="140">Lenox Hill East</option>
  		<option value="141">Lenox Hill West</option>
  		<option value="142">Lincoln Square East</option>
  		<option value="143">Lincoln Square West</option>
  		<option value="144">Little Italy/NoLiTa</option>
  		<option value="145">Long Island City/Hunters Point</option>
  		<option value="146">Long Island City/Queens Plaza</option>
  		<option value="147">Longwood</option>
  		<option value="148">Lower East Side</option>
  		<option value="149">Madison</option>
  		<option value="150">Manhattan Beach</option>
  		<option value="151">Manhattan Valley</option>
  		<option value="152">Manhattanville</option>
  		<option value="153">Marble Hill</option>
  		<option value="154">Marine Park/Floyd Bennett Field</option>
  		<option value="155">Marine Park/Mill Basin</option>
  		<option value="156">Mariners Harbor</option>
  		<option value="157">Maspeth</option>
  		<option value="158">Meatpacking/West Village West</option>
  		<option value="159">Melrose South</option>
  		<option value="160">Middle Village</option>
  		<option value="161">Midtown Center</option>
  		<option value="162">Midtown East</option>
  		<option value="163">Midtown North</option>
  		<option value="164">Midtown South</option>
  		<option value="165">Midwood</option>
  		<option value="166">Morningside Heights</option>
  		<option value="167">Morrisania/Melrose</option>
  		<option value="168">Mott Haven/Port Morris</option>
  		<option value="169">Mount Hope</option>
  		<option value="170">Murray Hill</option>
  		<option value="171">Murray Hill-Queens</option>
  		<option value="172">New Dorp/Midland Beach</option>
  		<option value="173">North Corona</option>
  		<option value="174">Norwood</option>
  		<option value="175">Oakland Gardens</option>
  		<option value="176">Oakwood</option>
  		<option value="177">Ocean Hill</option>
  		<option value="178">Ocean Parkway South</option>
  		<option value="179">Old Astoria</option>
  		<option value="180">Ozone Park</option>
  		<option value="181">Park Slope</option>
  		<option value="182">Parkchester</option>
  		<option value="183">Pelham Bay</option>
  		<option value="184">Pelham Bay Park</option>
  		<option value="185">Pelham Parkway</option>
  		<option value="186">Penn Station/Madison Sq West</option>
  		<option value="187">Port Richmond</option>
  		<option value="188">Prospect-Lefferts Gardens</option>
  		<option value="189">Prospect Heights</option>
  		<option value="190">Prospect Park</option>
  		<option value="191">Queens Village</option>
  		<option value="192">Queensboro Hill</option>
  		<option value="193">Queensbridge/Ravenswood</option>
  		<option value="194">Randalls Island</option>
  		<option value="195">Red Hook</option>
  		<option value="196">Rego Park</option>
  		<option value="197">Richmond Hill</option>
  		<option value="198">Ridgewood</option>
  		<option value="199">Rikers Island</option>
  		<option value="200">Riverdale/North Riverdale/Fieldston</option>
  		<option value="201">Rockaway Park</option>
  		<option value="202">Roosevelt Island</option>
  		<option value="203">Rosedale</option>
  		<option value="204">Rossville/Woodrow</option>
  		<option value="205">Saint Albans</option>
  		<option value="206">Saint George/New Brighton</option>
  		<option value="207">Saint Michaels Cemetery/Woodside</option>
  		<option value="208">Schuylerville/Edgewater Park</option>
  		<option value="209">Seaport</option>
  		<option value="210">Sheepshead Bay</option>
  		<option value="211">SoHo</option>
  		<option value="212">Soundview/Bruckner</option>
  		<option value="213">Soundview/Castle Hill</option>
  		<option value="214">South Beach/Dongan Hills</option>
  		<option value="215">South Jamaica</option>
  		<option value="216">South Ozone Park</option>
  		<option value="217">South Williamsburg</option>
  		<option value="218">Springfield Gardens North</option>
  		<option value="219">Springfield Gardens South</option>
  		<option value="220">Spuyten Duyvil/Kingsbridge</option>
  		<option value="221">Stapleton</option>
  		<option value="222">Starrett City</option>
  		<option value="223">Steinway</option>
  		<option value="224">Stuy Town/Peter Cooper Village</option>
  		<option value="225">Stuyvesant Heights</option>
  		<option value="226">Sunnyside</option>
  		<option value="227">Sunset Park East</option>
  		<option value="228">Sunset Park West</option>
  		<option value="229">Sutton Place/Turtle Bay North</option>
  		<option value="230">Times Sq/Theatre District</option>
  		<option value="231">TriBeCa/Civic Center</option>
  		<option value="232">Two Bridges/Seward Park</option>
  		<option value="233">UN/Turtle Bay South</option>
  		<option value="234">Union Sq</option>
  		<option value="235">University Heights/Morris Heights</option>
  		<option value="236">Upper East Side North</option>
  		<option value="237">Upper East Side South</option>
  		<option value="238">Upper West Side North</option>
  		<option value="239">Upper West Side South</option>
  		<option value="240">Van Cortlandt Park</option>
  		<option value="241">Van Cortlandt Village</option>
  		<option value="242">Van Nest/Morris Park</option>
  		<option value="243">Washington Heights North</option>
  		<option value="244">Washington Heights South</option>
  		<option value="245">West Brighton</option>
  		<option value="246">West Chelsea/Hudson Yards</option>
  		<option value="247">West Concourse</option>
  		<option value="248">West Farms/Bronx River</option>
  		<option value="249">West Village</option>
  		<option value="250">Westchester Village/Unionport</option>
  		<option value="251">Westerleigh</option>
  		<option value="252">Whitestone</option>
  		<option value="253">Willets Point</option>
  		<option value="254">Williamsbridge/Olinville</option>
  		<option value="255">Williamsburg (North Side)</option>
  		<option value="256">Williamsburg (South Side)</option>
  		<option value="257">Windsor Terrace</option>
  		<option value="258">Woodhaven</option>
  		<option value="259">Woodlawn/Wakefield</option>
  		<option value="260">Woodside</option>
  		<option value="261">World Trade Center</option>
  		<option value="262">Yorkville East</option>
  		<option value="263">Yorkville West</option>
  		<option value="264">N/A</option>
  		<option value="265">Outside of NYC</option>
    </select>

    <br><br>
    <input type="submit" value="Submit">
    </form>
</body>
</html>`
